### ISSUE TITLE
Adiciona ai

### ISSUE THREAD

**Issue by wiliamvj** [alexmoreno/telegram-br#70]
Adicione este grupo: 
https://t.me/javascripto

Grupo sobre Javascript e se universo (uma pitada de humor)

Tks a lot

**Comment by GenildoLopes** [comment]
Adiciona esse grupo:
[https://t.me/joinchat/P1JkThSirDJlKgJdgzyTFQ](url)
Grupo sobre o Semantic UI (Um Framework Front End)
